#! /usr/bin/env sh

# ---------------------------------------------------------------------------
# statusbar: a set of scripts for dwmblocks statusbar
# ---------------------------------------------------------------------------

_datetime() {
	date '+%I:%M ~ %A, %d %b'
}

case $1 in
	datetime)
		_datetime
		exit 0
		;;
	username)
		whoami
		exit 0
		;;
	* )
		echo "[unknown]"
		exit 1
		;;
esac
