#! /usr/bin/env bash

# ----------------------------------------------------------------------------
# update-xmenu: so the xmenu will sync with xdg application
# ----------------------------------------------------------------------------

XMENU_SCRIPT=${USRSCRIPT:-$HOME/.local/exe}/menu

read -r -d '' _usage_string <<EOF
#! /usr/bin/env sh

xmenu -i <<EOF | sh &
$(xdg-xmenu -t st)
EOF
echo "$_usage_string" > $XMENU_SCRIPT;echo 'EOF' >> $XMENU_SCRIPT;chmod +x $XMENU_SCRIPT
echo "refresh xclickroot"
killall -q xclickroot
setsid -f xclickroot -r $XMENU_SCRIPT
