vim.g.mapleader = ' '
vim.b.mapleader = ' '

vim.o.title = true
vim.o.titlestring = ' %t %m %f'
vim.o.clipboard = 'unnamedplus'
vim.o.mouse = 'a'
vim.o.completeopt = 'menuone,noselect'
vim.wo.number = false
vim.wo.relativenumber = true
vim.o.hidden = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.incsearch = true
vim.o.timeoutlen = 300
vim.wo.signcolumn = 'yes'
vim.cmd [[set shortmess+=c]]
vim.o.updatetime = 300
vim.o.autoindent = true
vim.o.expandtab = false
vim.bo.expandtab = false
vim.o.shiftwidth = 4
vim.bo.shiftwidth = 4
vim.o.smarttab = true
vim.o.softtabstop = 4
vim.bo.softtabstop =4
vim.o.termguicolors = true
vim.o.tabstop = 4
vim.bo.tabstop = 4
vim.o.showmode = false
vim.o.showcmd = false
vim.o.ruler = false
vim.o.laststatus = 2
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.hlsearch = false
vim.o.backup = false
vim.o.writebackup = false
vim.o.swapfile = false
vim.wo.list = true
vim.o.modelineexpr = true
vim.o.listchars = 'tab:▸ ,eol:¬,nbsp:␣,extends:…,precedes:<,extends:>,trail:·'
vim.wo.listchars = 'tab:▸ ,eol:¬,nbsp:␣,extends:…,precedes:<,extends:>,trail:·'
vim.o.wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite'
