add_newline = false

[character]
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"
vicmd_symbol = "[«](bold green)"

[username]
show_always = true
format = '[[\[](blue)$user[\]](blue)[:](bold black)]($style)'

[hostname]
ssh_only = false
format =  '[$hostname[:](bold black)](bold red)'
disabled = false

[line_break]
disabled = true
