#! /usr/bin/env sh

xmenu -i <<EOF | sh &
Accessories
	Neovim (Text Editor)	st -e nvim
	Passwords and Keys	seahorse
	Redshift (Color temperature adjustment)	redshift-gtk
Games
	Dwarf Fortress (Dwarf Fortress)	dwarffortress
Graphics
	GNU Image Manipulation Program (Image Editor)	gimp-2.10
Internet
	Brave (Web Browser)	brave
	Chromium (Web Browser)	/usr/bin/chromium
	Telegram Desktop	telegram-desktop --
Multimedia
	GTK Pipe Viewer	gtk-pipe-viewer
	mpv Media Player (Multimedia player)	mpv --player-operation-mode=pseudo-gui --
	PulseAudio Volume Control (Volume Control)	pavucontrol
	SimpleScreenRecorder	simplescreenrecorder --logfile
	SoundWire Server	SoundWireServer
Office
	Zathura	zathura
System
	Htop (Process Viewer)	st -e htop
Refresh	update-xmenu
Terminal	st
EOF
