#! /usr/bin/env bash

ffmpeg \
	-f x11grab \
	-s $(xdpyinfo | grep dimensions | awk '{ print $2;}') \
	-i :0.0 \
	-r 30 \
	-b:v 2M \
	-c:v libx264 \
	$HOME/dox/ffmpeg/$(date '+screencast_%Y-%m-%d_%H%M%S.mkv')
	# -c:a flac \
	# -f alsa -i default \
