#! /usr/bin/env bash

WALL_DIR="$XDG_DATA_HOME"/backgrounds

wallpath="$(sxiv -tb $WALL_DIR)"
case $wallpath in
	*.png)
		wallext="png"
		;;
	*.jpg)
		wallext="jpg"
		;;
	*.jpeg)
		wallext="jpeg"
		;;
	*)
		echo "unknown"
		exit 1
		;;
esac

rm -rf $XDG_CONFIG_HOME/wallpaper.png
rm -rf $XDG_CONFIG_HOME/wallpaper.jpg
rm -rf $XDG_CONFIG_HOME/wallpaper.jpeg
ln -sf $wallpath "$(echo $XDG_CONFIG_HOME/wallpaper.$wallext)"
