#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

wallset_int() {
	local wallpath=$(tr '\n' '\0' | xargs -0 echo)
	xwallpaper --zoom $wallpath
	echo $wallpath
}

case "$1" in
	"C-g")
		tr '\n' '\0' | xargs -0 gimp &
		;;
	"C-w")
		wallset_int
		;;
esac
