#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

wallset() {
	local wallpath=$(tr '\n' '\0' | xargs -0 echo)
	xwallpaper --zoom $wallpath
	echo $wallpath
	pkill -9 sxiv
}

case "$1" in
	"C-g") # C-x C-g
		tr '\n' '\0' | xargs -0 gimp &
		;;
	"w") # C-x w
		wallset
		;;
esac
