#! /usr/bin/env sh

# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.config/x11/startup ] && . ~/.config/x11/startup
[ -f ~/.config/x11/xresources ] && xrdb ~/.config/x11/xresources

exec dwm
# exec startlxde
